version: '2'

services:
    kf2:
        container_name: kf2
        image: dwurf/docker-kf2:latest
        # Uncomment this to skip auto-update
        #command: update validate
        #command: update -beta preview validate
        restart: always
        ports:
            - 0.0.0.0:20560:20560/udp
            - 0.0.0.0:27015:27015/udp
            - 0.0.0.0:7777:7777/udp
            - 0.0.0.0:8080:8080
        environment:
            - KF_DIFFICULTY=1
            - KF_GAME_LENGTH=1
            - KF_SERVER_NAME="My Public Server"
            - KF_MAP=KF-BioticsLab
            - KF_QUERY_PORT=27015
            - KF_PORT=7777
            - KF_WEBADMIN_PORT=8080
            - KF_BANNER_LINK="http:\/\/art.tripwirecdn.com\/TestItemIcons\/MOTDServer.png"
            - KF_MOTD="Welcome to our server!"
            - KF_WEBSITE_LINK="https:\/\/killingfloor2.com\/"
        volumes:
            - ./kf2server/:/home/steam/kf2server
            - ./kf2_steamdir/:/home/steam/steam
        logging:
            # limit logs retained on host to 25MB
            driver: "json-file"
            options:
                max-size: "500k"
                max-file: "50"
